steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - covid-data-scraper
  - --region=asia-east2
  - --runtime=nodejs8
  - --source=.
  - --trigger-topic=run-covid-data-scraper
  - --entry-point=execScrapeFunc