 name: 'gcr.io/cloud-builders/gcloud'
 args:
 — functions
 — deploy
 — — runtime=nodejs8
 — — trigger-topic
 — run-covid-data-scraper
 — — source=./ # Function source files
 — — entry-point=execScrapeFunc # Function entry point
 — execScrapeFunc # Function name
 waitFor: ['_']
 id: 'deploying-covid-scraper-function'